<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class GuruController extends Controller
{
    public function index()
    {
        $guru = collect([
            [
                'nama' => 'Drs. Nur Adi, M.Pd.',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1963-10-22',
                'jabatan' => 'Ketua Yayasan',
                'tmt' => '1985-07-15',
                'ijazah' => 'S1',
                'jurusan' => 'PAI/IV',
                'tahun' => '2001',
                'perguruan_tinggi' => 'IAI Al Aqidah Jakarta',
                'bidang_studi' => 'Aqidah Akhlak',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Nana Suryana, S.Ag.',
                'jk' => 'L',
                'tempat' => 'Lemah Abang',
                'tgl_lahir' => '1975-01-21',
                'jabatan' => 'Kepala Madrasah',
                'tmt' => '1995-07-14',
                'ijazah' => 'S1',
                'jurusan' => 'PAI/IV',
                'tahun' => '2001',
                'perguruan_tinggi' => 'IAIN Sunan Gunung Djati Bandung',
                'bidang_studi' => 'B. Indonesia',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'H. Jajay Suharto, S.Pd., MM',
                'jk' => 'L',
                'tempat' => 'Bandung',
                'tgl_lahir' => '1960-07-30',
                'jabatan' => 'Waka. Kurikulum',
                'tmt' => '2006-07-16',
                'ijazah' => 'S2',
                'jurusan' => 'Magister Manajemen',
                'tahun' => '2008',
                'perguruan_tinggi' => 'ST Manajemen IMMI Jakarta',
                'bidang_studi' => 'Matematika',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Ali Agung, S.Pd.I.',
                'jk' => 'L',
                'tempat' => 'Cikarang',
                'tgl_lahir' => '1988-06-11',
                'jabatan' => 'TU',
                'tmt' => '2008-07-14',
                'ijazah' => 'S1',
                'jurusan' => 'PAI/IV',
                'tahun' => '2012',
                'perguruan_tinggi' => 'STAI Haji Agus Salim',
                'bidang_studi' => 'Matematika',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Simson Abdul Muis, A.Md.',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1975-04-14',
                'jabatan' => 'Guru Bid. Study',
                'tmt' => '2008-07-14',
                'ijazah' => 'D3',
                'jurusan' => 'Tek. Komputer',
                'tahun' => '2001',
                'perguruan_tinggi' => 'STMIK Bani Saleh Bekasi',
                'bidang_studi' => 'TIK',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Sufyan Maulana, S.Ag.',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1973-06-08',
                'jabatan' => 'Guru Bid. Study',
                'tmt' => '2007-07-14',
                'ijazah' => 'S1',
                'jurusan' => 'Dakwah',
                'tahun' => '1997',
                'perguruan_tinggi' => 'STAI Babunnajah Pandeglang',
                'bidang_studi' => 'Fiqih',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Dede Bahrudin',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1987-12-30',
                'jabatan' => 'Waka. Sapras',
                'tmt' => '2016-07-18',
                'ijazah' => 'SMA',
                'jurusan' => '-',
                'tahun' => '-',
                'perguruan_tinggi' => '-',
                'bidang_studi' => 'SKI',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Zein Hadi, SH.',
                'jk' => 'P',
                'tempat' => 'Depok',
                'tgl_lahir' => '1996-06-18',
                'jabatan' => 'Guru Bid. Study',
                'tmt' => '2020-07-13',
                'ijazah' => 'S1',
                'jurusan' => 'Perbandingan Mazhab',
                'tahun' => '2020',
                'perguruan_tinggi' => 'UIN Syarif Hidayatullah Jakarta',
                'bidang_studi' => 'PKn',
                'alamat' => 'Sukakarya',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Suwarno Hidayat',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1972-07-23',
                'jabatan' => 'Waka. Humas',
                'tmt' => '2002-07-15',
                'ijazah' => 'SMA',
                'jurusan' => '-',
                'tahun' => '-',
                'perguruan_tinggi' => '-',
                'bidang_studi' => 'Bahasa Arab',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Mumuh Mukhtar Sodik',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1980-09-12',
                'jabatan' => 'Guru Bid. Study',
                'tmt' => '2018-07-16',
                'ijazah' => 'SMA',
                'jurusan' => '-',
                'tahun' => '-',
                'perguruan_tinggi' => '-',
                'bidang_studi' => 'Penjaskes',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Ghufron Achmadi, S.Th.I',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1982-05-07',
                'jabatan' => 'Guru Bid. Study',
                'tmt' => '2013-07-15',
                'ijazah' => 'S1',
                'jurusan' => 'Tafsir Hadits',
                'tahun' => '2009',
                'perguruan_tinggi' => 'UIN Sunan Kalijaga Yogyakarta',
                'bidang_studi' => "Al Qur'an Hadits",
                'alamat' => 'Cikarang Barat',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Een Supaenah, S.Pd.I',
                'jk' => 'P',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1969-03-08',
                'jabatan' => 'Guru Bid. Study',
                'tmt' => '2010-07-12',
                'ijazah' => 'S1',
                'jurusan' => 'PAI/IV',
                'tahun' => '2015',
                'perguruan_tinggi' => '-',
                'bidang_studi' => 'Seni Budaya',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Wardina, S.Pd.I',
                'jk' => 'P',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1990-12-22',
                'jabatan' => 'Guru Bid. Study',
                'tmt' => '2014-07-14',
                'ijazah' => 'S1',
                'jurusan' => 'PAI/IV',
                'tahun' => '2014',
                'perguruan_tinggi' => 'STAI Haji Agus Salim',
                'bidang_studi' => 'Prakarya',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Uu Dhia Uddin, S.Pd.',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1989-08-24',
                'jabatan' => 'Guru Bid. Study',
                'tmt' => '2014-07-14',
                'ijazah' => 'S1',
                'jurusan' => 'B. Inggris/IV',
                'tahun' => '2014',
                'perguruan_tinggi' => 'UIN Syarif Hidayatullah Jakarta',
                'bidang_studi' => 'B. Inggris',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'M. Mu’tashim Billah',
                'jk' => 'L',
                'tempat' => 'Jember',
                'tgl_lahir' => '1994-03-04',
                'jabatan' => 'Guru Bid. Study',
                'tmt' => '2016-07-18',
                'ijazah' => 'SMA',
                'jurusan' => '-',
                'tahun' => '2012',
                'perguruan_tinggi' => '-',
                'bidang_studi' => 'B. Inggris',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Nurjanah, S.Pd.',
                'jk' => 'P',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1992-11-04',
                'jabatan' => 'Guru Bid. Study',
                'tmt' => '2023-07-17',
                'ijazah' => 'S1',
                'jurusan' => 'Pendidikan Matematika',
                'tahun' => '2015',
                'perguruan_tinggi' => 'STKIP Kusumanegara',
                'bidang_studi' => 'Matematika',
                'alamat' => 'Sukatani',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Nursyamsiah, S.Ag.',
                'jk' => 'P',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1974-07-27',
                'jabatan' => 'Guru Bid. Study',
                'tmt' => '2018-07-16',
                'ijazah' => 'S1',
                'jurusan' => 'Dakwah',
                'tahun' => '1997',
                'perguruan_tinggi' => 'UIN Sunan Gunung Djati Bandung',
                'bidang_studi' => 'Aqidah Akhlak',
                'alamat' => 'Cikarang Barat',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Sihabudin, S.Ag.',
                'jk' => 'L',
                'tempat' => 'Cikarang',
                'tgl_lahir' => '1974-02-11',
                'jabatan' => 'Guru Bid. Study',
                'tmt' => '2018-07-16',
                'ijazah' => 'S1',
                'jurusan' => 'PAI/IV',
                'tahun' => '1998',
                'perguruan_tinggi' => 'UIN Sunan Gunung Djati Bandung',
                'bidang_studi' => 'IPA',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Heri Supriatna, S.Ag.',
                'jk' => 'L',
                'tempat' => 'Bandung',
                'tgl_lahir' => '1996-01-01',
                'jabatan' => 'Guru Bid. Study',
                'tmt' => '2020-07-13',
                'ijazah' => 'S1',
                'jurusan' => "Ilmu Al-Qur'an dan Tafsir",
                'tahun' => '2019',
                'perguruan_tinggi' => 'UIN Sunan Gunung Djati Bandung',
                'bidang_studi' => 'IPS',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Ik Pamungkas',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '2021-08-02',
                'jabatan' => 'Guru Bid. Study',
                'tmt' => '2023-07-17',
                'ijazah' => 'SMA',
                'jurusan' => '-',
                'tahun' => '-',
                'perguruan_tinggi' => '-',
                'bidang_studi' => 'Pramuka',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Marya Ulfah',
                'jk' => 'P',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1985-10-06',
                'jabatan' => 'TU',
                'tmt' => '2011-07-11',
                'ijazah' => 'SMA',
                'jurusan' => '-',
                'tahun' => '-',
                'perguruan_tinggi' => '-',
                'bidang_studi' => '-',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Mansur Sanusi, S.Pd.I',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1974-06-07',
                'jabatan' => 'Waka. Kesiswaan',
                'tmt' => '2002-07-15',
                'ijazah' => 'S1',
                'jurusan' => 'PAI/IV',
                'tahun' => '2015',
                'perguruan_tinggi' => '-',
                'bidang_studi' => 'Bahasa Arab',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Tety Haryati, S.Pd.',
                'jk' => 'P',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1979-07-27',
                'jabatan' => 'Guru Bid. Study',
                'tmt' => '2023-07-17',
                'ijazah' => 'S1',
                'jurusan' => '-',
                'tahun' => '-',
                'perguruan_tinggi' => '-',
                'bidang_studi' => 'Bahasa Indonesia',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Agus Salim, S.Pd.I',
                'jk' => 'L',
                'tempat' => 'Jember',
                'tgl_lahir' => '1981-06-11',
                'jabatan' => 'Guru BP',
                'tmt' => '2024-07-15',
                'ijazah' => 'S1',
                'jurusan' => 'PAI/IV',
                'tahun' => '2012',
                'perguruan_tinggi' => 'STAI Haji Agus Salim',
                'bidang_studi' => '-',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Slamet',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1960-08-22',
                'jabatan' => 'Penjaga Sekolah',
                'tmt' => '2015-07-13',
                'ijazah' => 'SD',
                'jurusan' => '-',
                'tahun' => '-',
                'perguruan_tinggi' => '-',
                'bidang_studi' => '-',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
        ]);

        return view('guru.index', compact('guru'));
    }
}