<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class GuruController extends Controller
{
    public function index()
    {
        $guru = collect([
            [
                'nama' => 'Drs. Nur Aidi, M.Pd.',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1963-10-22',
                'jabatan' => 'Ketua Yayasan',
                'bidang_studi' => 'Aqidah Akhlak',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Nana Suryana, S.Ag.',
                'jk' => 'L',
                'tempat' => 'Lemah Abang',
                'tgl_lahir' => '1975-01-21',
                'jabatan' => 'Kepala Madrasah',
                'bidang_studi' => 'B. Indonesia',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'H. Jajay Suharto, S.Pd., MM',
                'jk' => 'L',
                'tempat' => 'Bandung',
                'tgl_lahir' => '1960-07-30',
                'jabatan' => 'Waka. Kurikulum',
                'bidang_studi' => 'Matematika',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Ali Agung, S.Pd.I.',
                'jk' => 'L',
                'tempat' => 'Cikarang',
                'tgl_lahir' => '1988-06-11',
                'jabatan' => 'TU',
                'bidang_studi' => 'TIK',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Simson Abdul Muis, A.Md.',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1976-04-14',
                'jabatan' => 'Guru Bid. Study',
                'bidang_studi' => 'Fiqih',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Sufyan Maulana, S.Ag.',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1973-06-08',
                'jabatan' => 'Guru Bid. Study',
                'bidang_studi' => 'SKI',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Dede Bahrudin',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1987-12-30',
                'jabatan' => 'Waka. Sarpras',
                'bidang_studi' => 'PKn',
                'alamat' => 'Sukakarya',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Zein Hadi, SH.',
                'jk' => 'P',
                'tempat' => 'Depok',
                'tgl_lahir' => '1996-06-18',
                'jabatan' => 'Guru Bid. Study',
                'bidang_studi' => 'Bahasa Arab',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Suwarno Hidayat',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1972-07-23',
                'jabatan' => 'Waka. Humas',
                'bidang_studi' => 'Penjaskes',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Mumuh Mukhtar Sodik',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1980-09-12',
                'jabatan' => 'Guru Bid. Study',
                'bidang_studi' => "Al Qur'an Hadits",
                'alamat' => 'Cikarang Barat',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Ghufron Achmadi, S.Th.I',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1982-05-07',
                'jabatan' => 'Guru Bid. Study',
                'bidang_studi' => 'Seni Budaya',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Een Supaenah, S.Pd.I',
                'jk' => 'P',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1969-03-08',
                'jabatan' => 'Guru Bid. Study',
                'bidang_studi' => 'Prakarya',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Wardina, S.Pd.I',
                'jk' => 'P',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1990-12-22',
                'jabatan' => 'Guru Bid. Study',
                'bidang_studi' => 'B. Inggris',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Uu Dhia Uddin, S.Pd.',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1989-08-24',
                'jabatan' => 'Guru Bid. Study',
                'bidang_studi' => 'B. Inggris',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'M. Mu’tashim Billah',
                'jk' => 'L',
                'tempat' => 'Jember',
                'tgl_lahir' => '1994-03-04',
                'jabatan' => 'Guru Bid. Study',
                'bidang_studi' => 'Matematika',
                'alamat' => 'Sukatani',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Nurjanah, S.Pd.',
                'jk' => 'P',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1992-11-04',
                'jabatan' => 'Guru Bid. Study',
                'bidang_studi' => 'Aqidah Akhlak',
                'alamat' => 'Cikarang Barat',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Nursyamsiah, S.Ag.',
                'jk' => 'P',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1974-07-27',
                'jabatan' => 'Guru Bid. Study',
                'bidang_studi' => 'IPA',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Shibabudin, S.Ag.',
                'jk' => 'L',
                'tempat' => 'Cikarang',
                'tgl_lahir' => '1974-02-11',
                'jabatan' => 'Guru Bid. Study',
                'bidang_studi' => 'IPS',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Heri Supriatna, S.Ag.',
                'jk' => 'L',
                'tempat' => 'Bandung',
                'tgl_lahir' => '1996-01-01',
                'jabatan' => 'Guru Bid. Study',
                'bidang_studi' => 'Pramuka',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Iik Pamungkas',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '2021-08-02',
                'jabatan' => 'Guru Bid. Study',
                'bidang_studi' => '-',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Marya Ulfah',
                'jk' => 'P',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1985-10-06',
                'jabatan' => 'TU',
                'bidang_studi' => 'Bahasa Arab',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Mansur Sanusi, S.Pd.I',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1974-06-07',
                'jabatan' => 'Waka. Kesiswaan',
                'bidang_studi' => 'Bahasa Indonesia',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Tety Haryati, S.Pd.',
                'jk' => 'P',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1979-07-27',
                'jabatan' => 'Guru Bid. Study',
                'bidang_studi' => '-',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Agus Salim, S.Pd.I',
                'jk' => 'L',
                'tempat' => 'Jember',
                'tgl_lahir' => '1981-06-11',
                'jabatan' => 'Guru BP',
                'bidang_studi' => '-',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
            [
                'nama' => 'Slamet',
                'jk' => 'L',
                'tempat' => 'Bekasi',
                'tgl_lahir' => '1960-08-22',
                'jabatan' => 'Penjaga Sekolah',
                'bidang_studi' => '-',
                'alamat' => 'Cikarang Utara',
                'status' => 'Non PNS',
            ],
        ]);

        return view('guru', compact('guru'));
    }
}